# 노드 이미지를 최신 버전으로 가져옴
FROM node:latest as build

# working directory 지정
WORKDIR /app

# dependency 설치 
COPY . .
RUN yarn

EXPOSE 5173

# RUN yarn dev
CMD ["yarn", "dev"]
# 실제 환경 배포시 yarn build를 사용한다. 오늘 작성중인 Dockerfile은 개발용으로 작성되었다. (로컬 파일을 컨테이너화 한것과 동일함)